/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js projects and kept in source here so the
// workspace type-checks before the first local Next.js run.
